apiVersion: apps/v1
kind: Deployment
metadata:
  name: mb-atm-branch-location
  namespace: mnc-bank
  labels:
    app: mb-atm-branch-location
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mb-atm-branch-location
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mb-atm-branch-location
    spec:
      imagePullSecrets:
        - name: local
      containers:
        - name: mb-atm-branch-location
          image: docker.mncbank.co.id:5000/mb-atm-branch-location:v1.0.5
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
              name: 80tcp320341
          env:
            - name: ALLOW_SWAGGER
              value: "true"
            - name: Graylog_Host
              value: 10.5.99.123
            - name: Graylog_Port_Traffic
              value: "12214"
            - name: Graylog_Port_Error
              value: "12215"
            - name: mysql_name
              value: "mncmbank"
          envFrom:
            - secretRef:
                name: database-mysql
            - secretRef:
                name: aes-secret
            - secretRef:
                name: mysql-database-mncmbank
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:mnc-bank:mb-atm-branch-location"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  name: mb-atm-branch-location-nodeport
  namespace: mnc-bank
  labels:
    cattle.io/creator: norman
spec:
  ports:
  - name: mb-atm-branch-location-port
    nodePort: 31862
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mb-atm-branch-location
  type: NodePort